[package]
name = "toybox-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

egui = { version = "0.22", default-features=true }
egui-winit = "0.22"

toybox-gfx = { path = "../toybox-gfx" }
