[package]
name = "toybox-gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bumpalo = "3.12.1"

common.workspace = true
toybox-host.workspace = true

[dependencies.image]
version = "0.24"
features = ["png"]