[package]
name = "toybox-gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bumpalo = "3.12.1"

common = { git = "https://github.com/manpat/common-rs.git", version = ">=0.3" }
toybox-host = { path = "../toybox-host" }

[dependencies.image]
version = "0.24"
features = ["png"]