[package]
name = "toybox-vfs"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true

serde.workspace = true
serde_json.workspace = true