[package]
name = "toybox-input"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
winit.workspace = true
# gilrs = "0.10.2"

egui.workspace = true

common.workspace = true