[package]
name = "toybox-input"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28"

# TODO(pat.m): make this an optional feature, and conditionally opt in in toybox crate
egui = { version = "0.22", default-features=true }
