//! Everything relating to interacting with the graphics context, from low-level, more direct access,
//! to higher level utilities. The core of this system is [`context::Context`].
//! Other submodules that will likely be used often are [`buffer`] and [`mesh`].

use common::math::*;

pub mod raw {
	include!(concat!(env!("OUT_DIR"), "/gl_bindings.rs"));
}

pub mod context;
pub mod resources;
pub mod vao;
pub mod buffer;
pub mod texture;
pub mod framebuffer;
pub mod vertex;
pub mod shader;
pub mod query;
pub mod capabilities;
pub mod mesh;

pub use self::context::*;
pub use self::resources::*;
pub use self::vao::*;
pub use self::buffer::*;
pub use self::texture::*;
pub use self::framebuffer::*;
pub use self::vertex::*;
pub use self::shader::*;
pub use self::query::*;
pub use self::capabilities::*;
pub use self::mesh::*;


/// The kind of primitive to be generated by a draw call.
/// Used [`RenderState::draw_arrays`],  [`RenderState::draw_indexed`], and [`RenderState::draw_instances_indexed`].
pub enum DrawMode {
	Points,
	Lines,
	LineStrip,
	Triangles,
}

impl DrawMode {
	fn into_gl(self) -> u32 {
		match self {
			DrawMode::Points => raw::POINTS,
			DrawMode::Lines => raw::LINES,
			DrawMode::LineStrip => raw::LINE_STRIP,
			DrawMode::Triangles => raw::TRIANGLES,
		}
	}
}


bitflags::bitflags! {
	/// Which planes should be cleared by [`RenderState::clear`].
	pub struct ClearMode : u32 {
		const COLOR = 0b001;
		const DEPTH = 0b010;
		const STENCIL = 0b100;
		const ALL = 0b111;
	}
}

impl ClearMode {
	fn into_gl(self) -> u32 {
		let mut gl_value = 0;
		if self.contains(Self::COLOR) { gl_value |= raw::COLOR_BUFFER_BIT }
		if self.contains(Self::DEPTH) { gl_value |= raw::DEPTH_BUFFER_BIT }
		if self.contains(Self::STENCIL) { gl_value |= raw::STENCIL_BUFFER_BIT }
		gl_value
	}
}
